### ISSUE TITLE
Change registration endpoint BE

### ISSUE THREAD

**Issue by grygy** [davidkornel/FBAK#22]
- [ ] Change the registration endpoint to take the whole `User` object as described in the class diagram
- [ ] Return User with generated id 
- [ ] If email already exists throw an error

**Comment by lelleib** [comment]
So apart from userPublicKey, we need the following:
- lastname
- surname
- card

Correct?

**Comment by lelleib** [comment]
What does the Card type consist of?

**Comment by grygy** [comment]
I would send the whole User (apart from the id) from the class diagram. Card, transaction and voucher classes are in the class diagram as well. It would be easier to have the same model on the backend and app.

**Comment by grygy** [comment]
If you find something that you cannot do (circular dependency and so on), then I would we will change something in the model for the backend. Otherwise, I would stick to the class diagram.

**Comment by lelleib** [comment]
No problem, you can send any other fields (apart from the required) if it is easier, I will just ignore them. Should all the member names match **exactly**?
