### ISSUE TITLE
Fix server data model

### ISSUE THREAD

**Issue by FilippoComastri** [davidkornel/FBAK#23]
- change price to Double 
- Change ALL ID from string to UUID

**Comment by lelleib** [comment]
By changing ID type from string to UUID, do you mean the OpenAPI description? (JSON does not have a built-in UUID data type.)

**Comment by FilippoComastri** [comment]
We should have the possibility to pass UUID instead of String to the server during the checkout . Otherwise we have to change the data model from UUID to string for every id in the Checkout object . But the assignemente requires explicitly UUID .
________________________________
Da: Lellei Benedek ***@***.***>
Inviato: Saturday, April 8, 2023 9:28:42 AM
A: davidkornel/FBAK ***@***.***>
Cc: Filippo Comastri - ***@***.*** ***@***.***>; Author ***@***.***>
Oggetto: Re: [davidkornel/FBAK] Fix server data model (Issue #23)


By changing ID type from string to UUID, do you mean the OpenAPI description? (JSON does not have a built-in UUID data type.)
